CREATE DATABASE HOSPITAL;

CREATE TABLE MEDICO(
	IDMEDICO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(50)
);


CREATE TABLE PACIENTE(
	IDPACIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	CPF VARCHAR(15) NOT NULL,
	EMAIL VARCHAR(30),
	SEXO ENUM ('M', 'F') NOT NULL
);

CREATE TABLE EXAME(
	IDEXAME INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50) NOT NULL,
	OBSERVACAO VARCHAR(200),
	RESULTADO VARCHAR(400) NOT NULL,
	ID_PACIENTE INT,
	FOREIGN KEY(ID_PACIENTE)
	REFERENCES PACIENTE(IDPACIENTE)
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	NUMERO VARCHAR(13) NOT NULL,
	TIPO ENUM('RES', 'COM', 'CEL') NOT NULL,
	ID_PACIENTE INT,
	ID_MEDICO INT,
	FOREIGN KEY(ID_MEDICO)
	REFERENCES MEDICO(IDMEDICO),
	FOREIGN KEY(ID_PACIENTE)
	REFERENCES PACIENTE(IDPACIENTE)
);

CREATE TABLE MEDICAMENTO(
	IDMEDICAMENTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	TIPO VARCHAR(100) NOT NULL,
	DOSAGEM VARCHAR(100) NOT NULL,
	ID_PACIENTE INT,
	FOREIGN KEY(ID_PACIENTE)
	REFERENCES PACIENTE(IDPACIENTE)
);

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(100) NOT NULL,
	CIDADE VARCHAR(100) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	BAIRRO VARCHAR(100) NOT NULL,
	ID_PACIENTE INT UNIQUE,
	FOREIGN KEY(ID_PACIENTE)
	REFERENCES PACIENTE(IDPACIENTE)
);

CREATE TABLE PLANO(
	IDPLANO INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('PREMIUM', 'BASICO') NOT NULL,
	ID_PACIENTE INT UNIQUE,
	FOREIGN KEY(ID_PACIENTE)
	REFERENCES PACIENTE(IDPACIENTE)
);

CREATE TABLE CONSULTA(
	IDCONSULTA INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	TIPO ENUM('CONSULTA', 'RETORNO') NOT NULL,
	ID_PACIENTE INT,
	ID_MEDICO INT,
	FOREIGN KEY(ID_MEDICO)
	REFERENCES MEDICO(IDMEDICO),
	FOREIGN KEY(ID_PACIENTE)
	REFERENCES PACIENTE(IDPACIENTE)
);

desc consulta;
desc endereco;
desc exame;
desc medicamento;
DESC MEDICO;
DESC PACIENTE;
DESC PLANO;
DESC TELEFONE_MEDICO;
DESC TELEFONE_PASCIENTE;

select * from medico;
select * from consulta;
select * from endereco;
select * from exame;
select * from medicamento;
select * from plano;
select * from TELEFONE;
select * from paciente;